api_key: ""
dev_mode: false
base_url: "https://ark.cn-beijing.volces.com/api/v3/images/generations"
log_dir: "./logs"
auto_save: true
save_dir: "./output"

models:
  v5: "doubao-seedream-5-0-260128"
  v45: "doubao-seedream-4-5-251128"
  v4: "doubao-seedream-4-0-250828"

default:
  size: "1728x2304"
  output_format: "png"
  watermark: false